[package]
authors = ["Chevdor <chevdor@gmail.com>"]
description = "A tool to query your ssh config"
edition = "2021"
keywords = ["ssh", "chevdor", "cli"]
license = "MIT"
name = "sshq"
readme = "README.md"
repository = "https://github.com/chevdor/sshq"
version = "0.1.1"

[dependencies]
clap = {version = "3.0", features = ["derive", "env", "unicode", "cargo"]}
env_logger = "0.9"
log = "0.4"
serde = "1.0.136"
ssh_cfg = "0.3"
tokio = {version = "1.17", features = ["full"]}

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
