[package]
name = "sshq"
version = "0.0.2"
edition = "2021"
description = "A tool to query your ssh config"
license = "MIT"
repository = "https://github.com/chevdor/sshq"

[dependencies]
clap = {version = "3.0", features = ["derive", "env", "unicode", "cargo"]}
serde = "1.0.136"
ssh_cfg = "0.3"
tokio = { version = "1.17", features = ["full"] }
env_logger = "0.9"
log = "0.4"
