[package]
name = "sshq"
version = "0.0.1"
edition = "2021"
description = "A tool to query your ssh config"
license = "MIT"
repository = "https://github.com/chevdor/sshq"

[dependencies]
clap = "3.1"
serde = "1.0.136"
serde_json = "1.0.79"
ssh_cfg = "0.3"
tokio = { version = "1.17", features = ["full"] }
